# Generated by Django 4.2.23 on 2026-08-11 11:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriadespesa',
            name='orcamento_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Limite de gasto mensal nessa categoria, em R$. Deixe em branco pra não definir orçamento.', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='DespesaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dia_do_mes', models.PositiveSmallIntegerField(help_text='Dia do mês em que a despesa é lançada (ex: 5). Meses mais curtos usam o último dia disponível.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorrentes', to='financas.categoriadespesa')),
            ],
            options={
                'verbose_name': 'Despesa recorrente',
                'verbose_name_plural': 'Despesas recorrentes',
                'ordering': ['dia_do_mes', 'descricao'],
            },
        ),
        migrations.AddField(
            model_name='despesa',
            name='recorrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_geradas', to='financas.despesarecorrente'),
        ),
    ]
