# Generated by Django 4.2.23 on 2026-08-18 14:42

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financas', '0003_add_usuario_multi_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Nubank, Inter Black.', max_length=100)),
                ('limite', models.DecimalField(blank=True, decimal_places=2, help_text='Limite total do cartão, em BRL. Deixe em branco pra não acompanhar limite.', max_digits=12, null=True)),
                ('dia_fechamento', models.PositiveSmallIntegerField(help_text='Dia do mês em que a fatura fecha.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('dia_vencimento', models.PositiveSmallIntegerField(help_text='Dia do mês em que a fatura vence.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('ativo_flag', models.BooleanField(default=True, verbose_name='Ativo (não arquivado)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(help_text='Categoria usada na despesa gerada ao pagar uma fatura.', on_delete=django.db.models.deletion.PROTECT, related_name='cartoes', to='financas.categoriadespesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão de crédito',
                'verbose_name_plural': 'Cartões de crédito',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CompraCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('numero_parcelas', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('data_compra', models.DateField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='cartoes.cartaocredito')),
            ],
            options={
                'verbose_name': 'Compra no cartão',
                'verbose_name_plural': 'Compras no cartão',
                'ordering': ['-data_compra', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('paga', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='cartoes.cartaocredito')),
                ('despesa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fatura_cartao', to='financas.despesa')),
            ],
            options={
                'verbose_name': 'Fatura de cartão',
                'verbose_name_plural': 'Faturas de cartão',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('cartao', 'ano', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='ParcelaCompraCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='cartoes.compracartao')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='cartoes.faturacartao')),
            ],
            options={
                'verbose_name': 'Parcela de compra',
                'verbose_name_plural': 'Parcelas de compra',
                'ordering': ['numero'],
                'unique_together': {('compra', 'numero')},
            },
        ),
    ]
