# Generated by Django 4.2.23 on 2026-08-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Código na B3 (ex: PETR4) ou símbolo da cripto (ex: BTC).', max_length=15)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(choices=[('ACAO', 'Ação B3'), ('CRIPTO', 'Criptomoeda')], max_length=10)),
                ('coingecko_id', models.CharField(blank=True, help_text='ID do CoinGecko (ex: bitcoin, ethereum). Obrigatório só para criptomoedas.', max_length=50, null=True)),
                ('quantidade', models.DecimalField(decimal_places=8, max_digits=20)),
                ('preco_medio_compra', models.DecimalField(decimal_places=2, help_text='Preço médio de compra, em BRL.', max_digits=18)),
                ('ativo_flag', models.BooleanField(default=True, verbose_name='Ativo (não arquivado)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['tipo', 'ticker'],
                'unique_together': {('ticker', 'tipo')},
            },
        ),
    ]
