# Generated by Django 4.2.23 on 2026-08-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='data_aplicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='indexador',
            field=models.CharField(blank=True, choices=[('CDI', '% do CDI'), ('SELIC', '% da Selic'), ('PREFIXADO', 'Prefixado (taxa fixa ao ano)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='taxa_contratada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Para CDI/Selic: % do indexador contratado (ex: 110 = 110%% do CDI). Para Prefixado: taxa fixa ao ano, em %% (ex: 12.5).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='valor_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor aplicado, em BRL.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='preco_medio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço médio de compra, em BRL. Não se aplica a Renda Fixa.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Obrigatório para Ação, FII e Criptomoeda. Não se aplica a Renda Fixa.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='ticker',
            field=models.CharField(help_text='Código na B3 (ex: PETR4, MXRF11) ou símbolo da cripto (ex: BTC). Para renda fixa, use um rótulo livre (ex: CDB Banco X).', max_length=15),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='tipo',
            field=models.CharField(choices=[('ACAO', 'Ação B3'), ('FII', 'Fundo Imobiliário (FII)'), ('CRIPTO', 'Criptomoeda'), ('RENDA_FIXA', 'Renda Fixa (CDI/Selic/Prefixado)')], max_length=10),
        ),
    ]
