# Generated by Django 4.2.23 on 2026-08-11 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0002_ativo_data_aplicacao_ativo_indexador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrimonioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('valor_investido_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Snapshot de patrimônio',
                'verbose_name_plural': 'Snapshots de patrimônio',
                'ordering': ['data'],
            },
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='preco_medio_compra',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='quantidade',
        ),
        migrations.CreateModel(
            name='TransacaoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda')], max_length=6)),
                ('quantidade', models.DecimalField(decimal_places=8, max_digits=20)),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço por unidade nessa transação, em BRL.', max_digits=18)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='investimentos.ativo')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
