# Generated by Django 4.2.23 on 2026-08-11 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0003_patrimoniosnapshot_remove_ativo_preco_medio_compra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIVIDENDO', 'Dividendo'), ('JCP', 'Juros sobre Capital Próprio'), ('RENDIMENTO', 'Rendimento (FII)')], max_length=10)),
                ('valor_por_cota', models.DecimalField(decimal_places=6, help_text='Valor pago por ação/cota, em BRL.', max_digits=10)),
                ('data_com', models.DateField(help_text='Data-base — a quantidade que você tinha nesse dia é usada pra calcular o valor recebido.')),
                ('data_pagamento', models.DateField(blank=True, help_text='Data em que o valor efetivamente caiu na conta (opcional).', null=True)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proventos', to='investimentos.ativo')),
            ],
            options={
                'verbose_name': 'Provento',
                'verbose_name_plural': 'Proventos',
                'ordering': ['-data_com'],
            },
        ),
    ]
