# Generated by Django 4.2.23 on 2026-08-18 14:49

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investimentos', '0005_add_usuario_multi_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlocacaoAlvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACAO', 'Ação B3'), ('FII', 'Fundo Imobiliário (FII)'), ('CRIPTO', 'Criptomoeda'), ('RENDA_FIXA', 'Renda Fixa (CDI/Selic/Prefixado)')], max_length=10)),
                ('percentual_alvo', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes_alvo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alocação-alvo',
                'verbose_name_plural': 'Alocações-alvo',
                'unique_together': {('usuario', 'tipo')},
            },
        ),
    ]
