# Generated by Django 4.2.23 on 2026-08-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0006_alocacaoalvo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacaoativo',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=8, help_text='Preço por unidade nessa transação, em BRL.', max_digits=20),
        ),
    ]
