# Generated by Django 4.2.23 on 2026-08-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0007_alter_transacaoativo_preco_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='moeda',
            field=models.CharField(choices=[('BRL', 'Real (R$)'), ('USD', 'Dólar (US$)'), ('EUR', 'Euro (€)')], default='BRL', max_length=3),
        ),
    ]
