# Generated by Django 4.2.23 on 2026-08-18 14:23

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financas', '0003_add_usuario_multi_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Financiamento do carro, Empréstimo consignado Banco X.', max_length=150)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total tomado emprestado (principal), em BRL.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('taxa_juros', models.DecimalField(decimal_places=2, help_text='Taxa de juros em %% — ver "Período da taxa" pra dizer se é ao mês ou ao ano.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('periodo_taxa', models.CharField(choices=[('MENSAL', 'Ao mês'), ('ANUAL', 'Ao ano')], default='MENSAL', max_length=6)),
                ('sistema_amortizacao', models.CharField(choices=[('PRICE', 'Price (parcela fixa)'), ('SAC', 'SAC (parcela decrescente)')], default='PRICE', max_length=5)),
                ('numero_parcelas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data_primeira_parcela', models.DateField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Categoria usada nas despesas geradas ao pagar uma parcela.', on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='financas.categoriadespesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('data_vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_juros', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_amortizacao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, help_text='Saldo devedor logo após essa parcela.', max_digits=12)),
                ('paga', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('despesa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcela_emprestimo', to='financas.despesa')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='emprestimos.emprestimo')),
            ],
            options={
                'verbose_name': 'Parcela de empréstimo',
                'verbose_name_plural': 'Parcelas de empréstimo',
                'ordering': ['numero'],
                'unique_together': {('emprestimo', 'numero')},
            },
        ),
    ]
