# Generated by Django 4.2.23 on 2026-08-18 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_add_usuario_multi_tenant'),
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmortizacaoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('despesa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amortizacao_extra', to='financas.despesa')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizacoes_extras', to='emprestimos.emprestimo')),
            ],
            options={
                'verbose_name': 'Amortização extra',
                'verbose_name_plural': 'Amortizações extras',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
