# Generated by Django 4.2.23 on 2026-08-18 14:47

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Reserva de emergência, Viagem pra Europa.', max_length=150)),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data_alvo', models.DateField(blank=True, help_text='Data em que você quer atingir a meta (opcional).', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta financeira',
                'verbose_name_plural': 'Metas financeiras',
                'ordering': ['data_alvo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AporteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APORTE', 'Aporte'), ('RETIRADA', 'Retirada')], default='APORTE', max_length=8)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='metas.metafinanceira')),
            ],
            options={
                'verbose_name': 'Aporte de meta',
                'verbose_name_plural': 'Aportes de meta',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
