# Generated by Django 4.2.23 on 2026-08-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0007_alter_transacaoativo_preco_unitario'),
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metafinanceira',
            name='ativos',
            field=models.ManyToManyField(blank=True, help_text='Ativos da carteira que contam pro valor guardado dessa meta.', related_name='metas', to='investimentos.ativo'),
        ),
    ]
